#!/bin/bash
#SBATCH -J path
#SBATCH -o results/strong/path_2n.out
#SBATCH -e results/strong/path_2n.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=2
#SBATCH --get-user-env 
#SBATCH -t 00:10:00 
#SBATCH --mem-per-cpu=1000 
#SBATCH --partition=cs5220 

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
source /etc/profile.d/modules.sh 
module load openmpi-4.0.0 
cd $HOME/floyd-warshall 
./path.x -n 1200

