#!/bin/bash
#SBATCH -J path
#SBATCH -o results/weak/path_4n.out
#SBATCH -e results/weak/path_4n.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --tasks-per-node=1 
#SBATCH --cpus-per-task=4
#SBATCH --get-user-env 
#SBATCH -t 00:10:00 
#SBATCH --mem-per-cpu=1000 
#SBATCH --partition=cs5220 

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
source /etc/profile.d/modules.sh 
module load openmpi-4.0.0 
cd $HOME/floyd-warshall 
./path.x -n 800 

